### ISSUE TITLE
multiple versions of same element

### ISSUE THREAD

**Issue by kdabir** [Download/polymer-cdn#1]
how do you plan to support multiple versions of same element, let's say `1.0.1` and `1.0.2`?

**Comment by Download** [comment]
Hi @kdabir 

Versioning is easy with Git. We'll just create new releases regularly. If you have a look at the dropdown in the upper-left corner that says `Branch: master`, you'll see that it currently contains one version: `1.0.0` (under tags). You can (should) link directly to a specififc version of `polymer-cdn` so that you are fixed to that version.

Of course, as this is a collection of components, it means we can't version each component separately but instead have to make updates in which each component is updated to it's latest version. 

So, if there is a specififc element of which you want a new / different version than please let me know by creating an issue (or better even, pull request) with the version of the element you'd like to see added and I'll see what I can do to add it.

**Comment by Download** [comment]
Well I just checked and a lot has happened in Polymer development the past few weeks, so I updated everything to the latest versions and made a new release, `1.0.1`:
https://github.com/Download/polymer-cdn/tree/1.0.1

I'm hoping you'll find everything you need now. Let me know.

**Comment by kdabir** [comment]
cool, yeah I think all latest should be enough. fine grained control over individual element version would not be easy and it's okay. My primary use case was to import htmls on tools like codepen.io
